# Generated by Django 5.1.4 on 2025-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default=True, max_length=50, null=True)),
                ('productid', models.CharField(default=True, max_length=50, null=True)),
                ('totalprice', models.IntegerField(default=True, null=True)),
                ('pimg', models.ImageField(blank=True, null=True, upload_to='Cart_image')),
            ],
        ),
    ]
