# Generated by Django 5.1.4 on 2025-02-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_contactdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='mob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
